deploy:
  name: Deploy
  needs: build
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'

  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: production-files
        path: ./dist

    - name: Skip deployment (no-op)
      run: echo "No deployment necessary"
